version: '3'
services:
  postgres_first:
    image: postgres:latest
    container_name: postgres_${DATABASE_DATABASE}
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: 'America/Sao_Paulo'
    ports:
      - '${DATABASE_PORT}:5432'
    expose:
      - '${DATABASE_PORT}'
